# Generated by Django 3.1.2 on 2020-10-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atlassian_connect_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityContextToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('atlassian_user_account_id', models.CharField(max_length=50, verbose_name='Atlassian user id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('security_context', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_context_token', to='atlassian_connect_django.securitycontext')),
            ],
            options={
                'verbose_name': 'Token for atlassian security context',
                'verbose_name_plural': 'Tokens for atlassian security context',
                'abstract': False,
            },
        ),
    ]
